# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 700529d90bced327887955a72f1fc6ed065be611d303563161350170f66f8c750430cd14bddcd3f3c7e000de9bcd5755617498e08fea9ecf7738490771a989b3

test:
  secret_key_base: 61bb581904106d281f060f878484460ad0521e68a2bce34741d7b34b2b8afcba64f135591b5c33305ca30f6e435fb39de1ebcf3273d531633a4ba7f964ec463f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
